name: Generate Commit Invaders

on:
  # Roda automaticamente todos os dias à meia-noite
  schedule:
    - cron: '0 0 * * *'
  # Permite que você rode o script manualmente quando quiser
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Goblinlordx/commit-invaders@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: ${{ github.repository_owner }}
